version: '3.9'
services:

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - ./mongo/data:/data/db
    networks:
      - gecko_net

  redis:
    image: redis:latest
    container_name: redisdb
    networks:
      - gecko_net

  fastapi_server:
    build:
      context: .
      dockerfile: fastapi_app/Dockerfile
    container_name: fastapi
    environment:
      MONGONET: mongodb
      TOKEN: ${TOKEN}
      REDIS: redisdb
      MLFLOW_CLIENT: mlflow_client
      MLFLOW_SERVER: mlflow_server
    volumes:
      - ./fastapi_app:/app
    depends_on:
      - mongo
      - redis
    networks:
      - gecko_net

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi_server
    networks:
      - gecko_net

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: tg_bot
    env_file:
      - .env
    environment:
      FASTAPI: nginx
    volumes:
      - ./bot:/app
    depends_on:
      - nginx
    restart: always
    networks:
      - gecko_net

  mlflow_server:
    image: ubuntu/mlflow:2.1.1_1.0-22.04
    container_name: mlflow_server
    volumes:
      - ./mlflow_server/mlruns:/mlruns
      - ./mlflow_server/mlartifacts:/mlartifacts
    depends_on:
      - bot
    command: mlflow server -h 0.0.0.0 -p 5000
    networks:
      - gecko_net

  mlflow_client:
    build:
      context: .
      dockerfile: mlflow_client/Dockerfile
    container_name: mlflow_client
    environment:
      MLFLOW: mlflow_server
      FASTAPI: nginx
    volumes:
      - ./mlflow_client:/app
    depends_on:
      - mlflow_server
      - fastapi_server
    networks:
      - gecko_net

  scheduler:
    build:
      context: .
      dockerfile: scheduler/Dockerfile
    container_name: scheduler_sync
    env_file:
      - .env
    environment:
      MONGO: mongodb
      MLFLOW_CLIENT: mlflow_client
      MLFLOW_SERVER: mlflow_server
    volumes:
      - ./scheduler:/app
    depends_on:
      - mlflow_server
      - mlflow_client
      - mongo
    networks:
      - gecko_net


networks:
  gecko_net:
    external: true
    name: gecko_net