version: '3.9'
services:

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - ./mongo/data:/data/db
    networks:
      - gecko_net

  fastapi_server:
    build:
      context: .
      dockerfile: fastapi/Dockerfile
    container_name: fastapi
    env_file:
      - .env
    volumes:
      - ./fastapi:/app
    depends_on:
      - mongo
    networks:
      - gecko_net

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: tg_bot
    env_file:
      - .env
    volumes:
      - ./bot:/app
    depends_on:
      - fastapi_server
    restart: always
    networks:
      - gecko_net

networks:
  gecko_net:
    external: true
    name: gecko_net